### ISSUE TITLE
[改善要望]ボードのピンの役割がわかりにくい

### ISSUE THREAD

**Issue by belion-freee** [yohei04/solopacker#53]
ボードのピンに関して、選択すると国別に変わる仕様かと思いますが、わかりにくいかなと思いました。

全体的に説明が少ないのでヘルプを充実させた方がいいかと思います。複雑なアプリではないので、なんとなくでも使えますが。

**Comment by yohei04** [comment]
>ボードのピンに関して

やはりわかりにくいですよね、、
ピンにhoverしたら説明が出てくるようにしようかなと思ってます！

**Comment by belion-freee** [comment]
了解です。優先順位は低いので後でも大丈夫です。

**Comment by yohei04** [comment]
#60 で修正しました
